ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/store/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update-item/', views.updateItem, name='update_item'),
    path('process-order/', views.process_order, name='process_order'),
]

ecommerce/store/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=50, null=True)
    email = models.EmailField(blank=True, unique=True, error_messages={
        'unique': 'An account with this email alread exist.'
    })

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    isDigital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(upload_to='product_image/', null=True, blank=True)

    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def __str__(self):
        return self.name

    
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    isCompleted = models.BooleanField(default=False, blank=True, null=True)
    transaction_id = models.CharField(max_length=10, null=True);

    '''
    digital product no need to be shipped, so if there is only digital product then no shipping needed
    '''
    @property
    def shipping(self):
        shipping = False 
        orderItem = self.orderitem_set.all()
        for item in orderItem:
            if item.product.isDigital == False:
                shipping = True 
                break
        return shipping

    @property
    def get_grand_total(self):
        orderItem = self.orderitem_set.all()
        grand_total = sum([(item.quantity * item.product.price) for item in orderItem])
        return grand_total 
    
    @property
    def get_total_item(self):
        orderItem = self.orderitem_set.all()
        total_quantity = sum([item.quantity for item in orderItem])
        return total_quantity


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    @property
    def get_item_total(self):
        total = self.quantity * self.product.price 
        return total



class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=100, null=False)
    city = models.CharField(max_length=50, null=False)
    state = models.CharField(max_length=50, null=False)
    zipcode = models.CharField(max_length=20, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address



        

ecommerce/store/views.py
from ctypes import addressof
import json
from math import prod
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import datetime
from .models import *
from .utils import cartData, cookieCart


# Create your views here.
def store(request):
    data = cartData(request)
    total_item = data['total_item']
    order = data['order']
    items = data['items']
        
    products = Product.objects.all()
    context = {'products': products, 'total_item': total_item}
    return render(request,'store/store.html', context=context)

def cart(request):
    data = cartData(request)
    total_item = data['total_item']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'total_item': total_item}
    return render(request,'store/cart.html', context=context)

def checkout(request):
    data = cartData(request)
    total_item = data['total_item']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'total_item': total_item}

    return render(request,'store/checkout.html', context=context)


def updateItem(request):
    data = json.loads(request.body)
    product_id = data['product_id']
    action = data['action']

    print('Action:', action)
    print('Product Id:', product_id)

    customer = request.user.customer
    product = Product.objects.get(id=product_id)
    print(product)
    order, created = Order.objects.get_or_create(customer=customer, isCompleted=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
    print(orderItem.quantity)

    if action == 'add':
        orderItem.quantity += 1
    elif action == 'remove':
        orderItem.quantity -= 1

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)

def process_order(request):
    data = json.loads(request.body)
    print(data)

    transaction_id = datetime.datetime.now().timestamp();

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, isCompleted=False)
        total = float(data['form']['total'])
        order.transaction_id = transaction_id

    else:
        print("COOKIES", request.COOKIES)
        name = data['form']['name']
        email = data['form']['email']

        cookieData = cookieCart(request)
        items = cookieData['items']

        customer, created = Customer.objects.get_or_create(email=email)
        customer.name = name
        customer.save()

        order = Order.objects.create(customer=customer, isCompleted=False)

        for item in items:
            product = Product.objects.get(id=item['product']['id'])
            orderItem = OrderItem.objects.create(product=product, order=order, quantity=item['quantity'])

    if total == order.get_grand_total:
        order.isCompleted = True 
    
    order.save() 

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer = customer,
            order = order, 
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            zipcode = data['shipping']['zipcode'],
        )
    return JsonResponse("Payment success...", safe=False)  

ecommerce/store/templates/store/cart.html
{% extends 'store/main.html' %}

{% load static %}
{% load calc_total %}

{% block title %}
Cart
{% endblock %}

{% block content %}

<div class="box-element mt-5">
    <a class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>
    <br>
    <br>
    <table class="table">
        <tr>
            <th>
                <h5>Items: <strong>{{order.get_total_item}}</strong></h5>
            </th>
            <th>
                <h5>Total:<strong> ${{order.get_grand_total|floatformat:2}}</strong></h5>
            </th>
            <th>
                <a style="float:right; margin:5px;" class="btn btn-success"
                    href="{% url 'store:checkout' %}">Checkout</a>
            </th>
        </tr>
    </table>
</div>

<div class="box-element mt-3">
    <div class="cart-row">
        <div style="flex:2"></div>
        <div style="flex:2"><strong>Item</strong></div>
        <div style="flex:1"><strong>Price</strong></div>
        <div style="flex:1"><strong>Quantity</strong></div>
        <div style="flex:1"><strong>Total</strong></div>
    </div>

    {% for item in items %}
    <div class="cart-row">
        <div style="flex:2"><img class="row-image" src="{{ item.product.imageUrl }}"></div>
        <div style="flex:2">
            <p>{{item.product.name}}</p>
        </div>
        <div style="flex:1">
            <p>${{item.product.price|floatformat:2}}</p>
        </div>
        <div style="flex:1">
            <p class="quantity">{{item.quantity}}</p>
            <div class="quantity">
                <span data-action="add" data-product={{item.product.id}} class="chg-quantity update-cart">&#8593;</span>
                <span data-action="remove" data-product={{item.product.id}}
                    class="chg-quantity update-cart">&#8595;</span>
            </div>
        </div>
        <div style="flex:1">
            <p>${{item.get_item_total|floatformat:2}}</p>
            <!-- <p>${{item.quantity|item_total:item.product.price|floatformat:2 }}</p> -->
        </div>
    </div>
    {% endfor %}
    {% endblock %}

ecommerce/store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}

{% block title %}
Checkout products
{% endblock %}

{% block content %}
<div class="row mt-5">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                <div id="user-info">
                    <div class="form-field">
                        <input required class="form-control" id="name" type="text" name="name" placeholder="Name..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" id="email" type="email" name="email" placeholder="Email..">
                    </div>
                </div>

                <div id="shipping-info">
                    <hr>
                    <p>Shipping Information:</p>
                    <hr>
                    <div class="form-field">
                        <input class="form-control" type="text" name="address" placeholder="Address.." required>
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="city" placeholder="City.." required>
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="state" placeholder="State.." required>
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="zipcode" placeholder="Zip code.." required>
                    </div>
                </div>
                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
            </form>
        </div>
        <br>
        <div class="box-element hidden" id="payment-info">
            <small>Paypal Options</small>
            <div id="paypal-button-container"></div>
            <!-- <button class="btn btn-primary make-payment-btn" onclick="submitFormData()">Make Payment</button> -->
        </div>

    </div>

    <div class="col-lg-6">
        <div class="box-element">

            <a class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
            <hr>
            <h3>Order Summary</h3>
            <hr>
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageUrl}}"></div>
                <div style="flex:2">
                    <p>{{item.product.name}}</p>
                </div>
                <div style="flex:1">
                    <p>${{item.product.price}}</p>
                </div>
                <div style="flex:1">
                    <p>x{{item.quantity}}</p>
                </div>
            </div>
            {% endfor %}
            <h5>Items: {{order.get_total_item}}</h5>
            <h5>Total: ${{order.get_grand_total|floatformat:2}}</h5>

        </div>
    </div>
</div>

<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>

<script>
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        // Set up the transaction
        createOrder: function (data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: '88.44'
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function (data, actions) {
            return actions.order.capture().then(function (orderData) {
                // Successful capture! For demo purposes:
                console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                var transaction = orderData.purchase_units[0].payments.captures[0];
                alert('Transaction ' + transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

                // Replace the above to show a success message within this page, e.g.
                // const element = document.getElementById('paypal-button-container');
                // element.innerHTML = '';
                // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                // Or go to another URL:  actions.redirect('thank_you.html');
            });
        }


    }).render('#paypal-button-container');
</script>

<script type="text/javascript">
    let shipping = '{{order.shipping}}'
    let total = '{{order.get_grand_total|floatformat:2}}'

    if (shipping == 'False') {
        document.getElementById('shipping-info').innerHTML = ''
    }

    if (user != 'AnonymousUser') {
        const loggedInUserName = document.getElementById('name');
        const loggedInUserEmail = document.getElementById('email');

        loggedInUserName.value = '{{request.user.customer.name}}';
        loggedInUserEmail.value = '{{request.user.customer.email}}';

        loggedInUserName.disabled = true;
        loggedInUserEmail.disabled = true;
    }

    const form = document.getElementById('form');

    form.addEventListener('submit', function (e) {
        e.preventDefault();
        document.getElementById('form-button').classList.add('hidden');
        document.getElementById('payment-info').classList.remove('hidden');
    })

    function submitFormData() {
        console.log("form data is submitting...");

        const userFormData = {
            name: null,
            email: null,
            total: total,
        };

        const shippingInfo = {
            'address': null,
            'state': null,
            'city': null,
            'zipcode': null,
        }

        if (shipping != 'False') {
            shippingInfo.address = form.address.value;
            shippingInfo.state = form.state.value;
            shippingInfo.city = form.city.value;
            shippingInfo.zipcode = form.zipcode.value;
        }

        if (user == 'AnonymousUser') {
            userFormData.name = form.name.value;
            userFormData.email = form.email.value;
        } else {
            userFormData.name = '{{request.user.customer.name}}';
            userFormData.email = '{{request.user.customer.email}}';
        }

        const url = '/process-order/';
        fetch(url, {
            method: "POST",
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify({
                form: userFormData,
                shipping: shippingInfo,
            })
        }).then(response => response.json())
            .then(data => {
                alert('Transaction Completed');

                cart = {}
                document.cookie = "cart=" + JSON.stringify(cart) + ";domain=;path=/";

                window.location.href = "{% url 'store:store' %}";
            })

    }

</script>

{% endblock %}



<!-- const loggedInUserName = document.getElementsByName('name');
const loggedInUserEmail = document.getElementsByName('email');

loggedInUserName.value = userFormData.name;
loggedInUserEmail.value = userFormData.email;

loggedInUserName.disabled = true;
loggedInUserEmail.disabled = true; -->

ecommerce/store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

    <!-- bootstrap  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>

    <!-- custom javascript code here -->
    <script type="text/javascript">
        let user = '{{ request.user }}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');

        // get cookies function
        function getCookie(name) {
            let cookieArr = document.cookie.split(';');
            for (let i = 0; i < cookieArr.length; i++) {
                let cookiePair = cookieArr[i].split('=');
                if (name == cookiePair[0].trim()) {
                    return decodeURIComponent(cookiePair[1])
                }
            }

            return null;
        }

        let cart = JSON.parse(getCookie('cart'));
        if (cart == undefined) {
            cart = {};
            console.log('Cart was created !');
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }

        console.log('Cart', cart);
    </script>
</head>

<body>
    <nav style="background-color: #05373c !important;" id="navigation-bar"
        class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container-fluid">
            <a style="color: #fff !important;" class="navbar-brand" href="{% url 'store:store' %}">TechECOM</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a style="color: #fff !important;" class="nav-link active" aria-current="page"
                            href="{% url 'store:store' %}">Store</a>
                    </li>

                </ul>
                <div class="d-flex">
                    <a href="{% url 'admin:index' %}"><button class="btn btn-success">Login</button></a>
                    <a href="{% url 'store:cart' %}"><img src="{% static 'image/cart.png' %}" alt="cart"
                            id="cart-icon" /></a>
                    <p id="cart-total">{{total_item}}</p>
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %} {% endblock %}
    </div>




    <!-- bootstrap javascript  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>

    <script src="{% static 'js/cart.js' %}"></script>

</body>

</html>

ecommerce/store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}

{% block title %}
Store
{% endblock %}

{% block content %}
<div class="row mt-4 mb-4">
    {% for product in products %}
    <div class="col-lg-4 mt-4">
        <img class="thumbnail" src="{{ product.imageUrl }}">
        <div class="box-element product">
            <h6><strong>{{product.name}}</strong></h6>
            <hr>

            <button data-product={{product.id}} data-action="add"
                class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
            <a class="btn btn-outline-success" href="#">View</a>
            <h4 style="display: flex"><strong>${{product.price|floatformat:2}}</strong></h4>

        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}